server:
  port: 8080
  servlet:
    context-path: /springboot

spring:
  redis:
    host: 39.97.246.154
    port: 6379
    password: 123456
    timeout: 10000
    jedis:
      pool:
        max-idle: 300
        max-active: 600
        min-idle: 50
        max-wait: 300
    testOnBorrow: true